version: '3.8' 

services:
  frontend:
    build: ./my-frontend-app
    ports:
      - "3000:80"
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000/api/ 

  backend:
    build: ./my-backend-app
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db 
      MYSQL_PORT: 3306
      DJANGO_SECRET_KEY: "your_secret_key_here_for_development_only"
      DJANGO_ALLOWED_HOSTS: "*" 
      DJANGO_DEBUG: "True" 

    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password # Root password for MySQL
      MYSQL_DATABASE: mydatabase        # Database name to create
      MYSQL_USER: user                  # User for the database
      MYSQL_PASSWORD: password          # Password for the user
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data:
